[project]
name = "getKST"
version = "1.1.0"
description = "A Python package that returns datetime values ​​for the Asia/Seoul region."
readme = "README.md"
authors = [
    { name = "HaeengIn", email = "haeengin@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "tzdata>=2026.4; sys_platform == 'win32'",
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.scripts]
getkst = "getkst:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
